name: SimpleLumberjack
version: '0.3'
author: SnowzNZ
main: me.snowznz.simplelumberjack.SimpleLumberjack
api-version: '1.20'
website: "https://github.com/SnowzNZ/SimpleLumberjack"
description: A "Simple" plugin that cuts down trees as if you were a Lumberjack.
